language: groovy

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

dist: precise

script: ./gradlew check -x groovydoc

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
